package com.ecrea.potionmorepotion.network;

import com.ecrea.potionmorepotion.effect.ModMobEffects;
import net.minecraft.core.BlockPos;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.TickTask;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LightningBolt;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.UseAnim;
import net.minecraft.world.level.block.BaseFireBlock;
import net.minecraftforge.network.NetworkEvent;

import java.util.function.Supplier;

/**
 * Packet sent from client to server every tick while the player holds right-click
 * with the Lightning Blessing (Blessing of Lightning) active.
 * Spawns a lightning bolt at the target location up to 100 blocks away.
 * If the player is sneaking, fire blocks generated by the strike are extinguished.
 */
public class LightningAttackPacket {

    private final double targetX;
    private final double targetY;
    private final double targetZ;
    private final boolean isSneaking;

    public LightningAttackPacket(double targetX, double targetY, double targetZ, boolean isSneaking) {
        this.targetX = targetX;
        this.targetY = targetY;
        this.targetZ = targetZ;
        this.isSneaking = isSneaking;
    }

    public LightningAttackPacket(FriendlyByteBuf buf) {
        this.targetX = buf.readDouble();
        this.targetY = buf.readDouble();
        this.targetZ = buf.readDouble();
        this.isSneaking = buf.readBoolean();
    }

    public void toBytes(FriendlyByteBuf buf) {
        buf.writeDouble(this.targetX);
        buf.writeDouble(this.targetY);
        buf.writeDouble(this.targetZ);
        buf.writeBoolean(this.isSneaking);
    }

    public boolean handle(Supplier<NetworkEvent.Context> supplier) {
        NetworkEvent.Context context = supplier.get();
        context.enqueueWork(() -> {
            ServerPlayer player = context.getSender();
            if (player == null) {
                return;
            }

            // Verify active lightning_blessing
            var effectObj = ModMobEffects.EFFECTS.get("lightning_blessing");
            if (effectObj == null || !player.hasEffect(effectObj.get())) {
                return;
            }

            // Prioritize shield, bow, food, etc.
            if (player.isUsingItem()) {
                ItemStack usingItem = player.getUseItem();
                UseAnim anim = usingItem.getUseAnimation();
                if (anim != UseAnim.NONE) {
                    return;
                }
            }

            // Check range limit (up to ~120 blocks)
            if (player.distanceToSqr(this.targetX, this.targetY, this.targetZ) > 120.0 * 120.0) {
                return;
            }

            ServerLevel level = player.serverLevel();

            LightningBolt bolt = EntityType.LIGHTNING_BOLT.create(level);
            if (bolt == null) {
                return;
            }

            bolt.moveTo(this.targetX, this.targetY, this.targetZ);
            bolt.setCause(player);
            level.addFreshEntity(bolt);

            // If sneaking, prevent fire blocks on the ground
            if (this.isSneaking) {
                BlockPos strikePos = BlockPos.containing(this.targetX, this.targetY, this.targetZ);
                cleanFireAround(level, strikePos);
                if (player.getServer() != null) {
                    player.getServer().tell(new TickTask(player.getServer().getTickCount() + 1, () -> cleanFireAround(level, strikePos)));
                    player.getServer().tell(new TickTask(player.getServer().getTickCount() + 2, () -> cleanFireAround(level, strikePos)));
                }
            }
        });
        return true;
    }

    private static void cleanFireAround(ServerLevel level, BlockPos center) {
        for (BlockPos pos : BlockPos.betweenClosed(center.offset(-3, -2, -3), center.offset(3, 3, 3))) {
            if (level.getBlockState(pos).getBlock() instanceof BaseFireBlock) {
                level.removeBlock(pos, false);
            }
        }
    }
}
