package com.ecrea.potionmorepotion.network;

import com.ecrea.potionmorepotion.effect.ModMobEffects;
import net.minecraft.core.BlockPos;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.TickTask;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.damagesource.DamageTypes;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LightningBolt;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.UseAnim;
import net.minecraft.world.level.block.BaseFireBlock;
import net.minecraft.world.phys.AABB;
import net.minecraftforge.network.NetworkEvent;

import java.util.List;
import java.util.function.Supplier;

/**
 * Packet sent from client to server every tick while the player holds right-click
 * with the Lightning Blessing (Blessing of Lightning) active.
 * Spawns a lightning bolt at the target location up to 100 blocks away.
 * If the player is sneaking, fire blocks generated by the strike are extinguished.
 */
public class LightningAttackPacket {

    private final double targetX;
    private final double targetY;
    private final double targetZ;
    private final boolean isSneaking;

    public LightningAttackPacket(double targetX, double targetY, double targetZ, boolean isSneaking) {
        this.targetX = targetX;
        this.targetY = targetY;
        this.targetZ = targetZ;
        this.isSneaking = isSneaking;
    }

    public LightningAttackPacket(FriendlyByteBuf buf) {
        this.targetX = buf.readDouble();
        this.targetY = buf.readDouble();
        this.targetZ = buf.readDouble();
        this.isSneaking = buf.readBoolean();
    }

    public void toBytes(FriendlyByteBuf buf) {
        buf.writeDouble(this.targetX);
        buf.writeDouble(this.targetY);
        buf.writeDouble(this.targetZ);
        buf.writeBoolean(this.isSneaking);
    }

    public boolean handle(Supplier<NetworkEvent.Context> supplier) {
        NetworkEvent.Context context = supplier.get();
        context.enqueueWork(() -> {
            ServerPlayer player = context.getSender();
            if (player == null) {
                return;
            }

            // Verify active lightning_blessing
            var effectObj = ModMobEffects.EFFECTS.get("lightning_blessing");
            if (effectObj == null || !player.hasEffect(effectObj.get())) {
                return;
            }

            // Prioritize shield, bow, food, etc.
            if (player.isUsingItem()) {
                ItemStack usingItem = player.getUseItem();
                UseAnim anim = usingItem.getUseAnimation();
                if (anim != UseAnim.NONE) {
                    return;
                }
            }

            // Check range limit (up to ~120 blocks)
            if (player.distanceToSqr(this.targetX, this.targetY, this.targetZ) > 120.0 * 120.0) {
                return;
            }

            ServerLevel level = player.serverLevel();

            LightningBolt bolt = EntityType.LIGHTNING_BOLT.create(level);
            if (bolt == null) {
                return;
            }

            bolt.moveTo(this.targetX, this.targetY, this.targetZ);
            bolt.setCause(player);

            boolean sneaking = this.isSneaking || player.isShiftKeyDown() || player.isCrouching();
            if (sneaking) {
                // Completely prevents vanilla LightningBolt.spawnFire() from placing any fire blocks!
                bolt.setVisualOnly(true);
                bolt.addTag("no_fire");
            }
            level.addFreshEntity(bolt);

            if (sneaking) {
                // Extinguish any existing fire in the area
                BlockPos strikePos = BlockPos.containing(this.targetX, this.targetY, this.targetZ);
                cleanFireAround(level, strikePos);

                // Because visualOnly disables vanilla entity detection, directly damage entities without setting them on fire!
                AABB box = new AABB(this.targetX - 3.0D, this.targetY - 3.0D, this.targetZ - 3.0D,
                                    this.targetX + 3.0D, this.targetY + 9.0D, this.targetZ + 3.0D);
                List<Entity> list = level.getEntities(bolt, box, Entity::isAlive);

                var damageTypeHolder = level.registryAccess()
                        .registryOrThrow(Registries.DAMAGE_TYPE)
                        .getHolderOrThrow(DamageTypes.LIGHTNING_BOLT);
                DamageSource source = new DamageSource(damageTypeHolder, bolt, player);
                var lightningObj = ModMobEffects.EFFECTS.get("lightning_blessing");

                for (Entity target : list) {
                    if (target == player) {
                        continue;
                    }
                    if (target instanceof LivingEntity living && lightningObj != null && living.hasEffect(lightningObj.get())) {
                        continue;
                    }
                    target.hurt(source, bolt.getDamage());
                    target.clearFire(); // Completely extinguish entity so zero fire is attached
                }
            }
        });
        return true;
    }

    private static void cleanFireAround(ServerLevel level, BlockPos center) {
        for (BlockPos pos : BlockPos.betweenClosed(center.offset(-3, -2, -3), center.offset(3, 4, 3))) {
            if (level.getBlockState(pos).getBlock() instanceof BaseFireBlock) {
                level.removeBlock(pos, false);
            }
        }
    }
}
